sudo: required

services:
  - docker

language: java
jdk: openjdk8
  
script:
  - ./gradlew build --scan -s
  - docker build -t java-app .
after_success:
  - docker build -t registry.docker.com/cruxiu/demo-app .
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.docker.com
  - docker push registry.docker.com/cruxiu/demo-app
